### ISSUE TITLE
panic: no such file or directory

### ISSUE THREAD

**Issue by Daavidaviid** [go-pg/migrations#59]
Hi,
I've encountered an issue, and it seems like it's coming from this library.
It used to work perfectly until I switched from `GOPATH` to `go.mod`, now everytime I try to deploy my binary I ended get this error at runtime when launching it : 

```
panic: open /Users/MY_USERNAME/workspace/PROJECT_NAME/api/migration: no such file or directory

goroutine 1 [running]:
github.com/go-pg/migrations.(*Collection).MustRegister(...)
        /Users/MY_USERNAME/golang/pkg/mod/github.com/go-pg/migrations@v6.7.2+incompatible/collection.go:326
github.com/go-pg/migrations.MustRegister(0xc00012bf58, 0x2, 0x2)
        /Users/MY_USERNAME/golang/pkg/mod/github.com/go-pg/migrations@v6.7.2+incompatible/default.go:31 +0x7f
api/migration.init.0()
        /Users/MY_USERNAME/workspace/PROJECT_NAME/api/migration/001_initial.go:13 +0x5d
```

Here is what is in 001_initial.go:13 : 

```
package migration

import (
	"log"

	"github.com/go-pg/migrations"
	packr "github.com/gobuffalo/packr/v2"
)

var MigrationBox = packr.New("Migrations Box", "../../database/migrationsAPI")

func init() {
	migrations.MustRegisterTx(func(db migrations.DB) error { // <-- Line 13
		log.Println("Running 001_initial.up.sql...")

		migrationContent, err := MigrationBox.FindString("001_initial_up.sql")
		if err != nil {
			return err
		}

		_, err = db.Exec(migrationContent)
		return err
	}, func(db migrations.DB) error {
		log.Println("Running 001_initial.down.sql...")

		migrationContent, err := MigrationBox.FindString("001_initial_down.sql")
		if err != nil {
			return err
		}

		_, err = db.Exec(migrationContent)
		return err
	})
}

```

I don't think it comes from packr2 because It's working locally, even when I move the binary into another location on my machine.

Thanks for your help.

**Comment by ernsheong** [comment]
@Daavidaviid I am also seeing this error after migrating to go modules.
